Messages:
  ChatAlreadyRegistered: "Chat already registered! Type /new command to play."
  ChatNotExists: "Chat is not registered! Type /start command to register."
  ChatCreatedSuccessfully: "Chat was created successfully! Type /new command to start the game."
  ChatHasActiveGame: "Chat already has active game! Please type /draw or wait until active game is over."
  ChatHasNoActiveGame: "Chat has no active game! Please type /new to start one."

  Blackjack: "*BLACKJACK!*"
  GameOver: "*Game over!* Here is the statistics:"
  Win: "*Win* (+1)"
  Lose: "_Lose_ (-1)"
  Push: "Push (0)"
  BlackjackResult: "*Blackjack* (+2)"

  PlayerCantDraw: "*You cannot draw more cards!*"
  PlayerHand: "@%s hand:"
  PlayerHandBusted: "*BUSTED!*"
  PlayerAlreadyStopped: "@%s, you are already stopped drawing cards."
  PlayerAlreadyBusted: "@%s, you are busted."
  StoppedDrawing: "@%s stopped drawing! Waiting for other players to stop or to get *busted*..."

  DealerHand: "*Dealer* hand:"
  DealerBlackjack: "*Dealer* has *BLACKJACK!*"
  GameStartHint: "Type /new command to start a new game."
  GameEnterHint: "Type /draw command to enter the game."

  TopPlayers: "*Top* players:"
App:
  NumOfDecks: 6
